server:
  port: 3000

spring:
  application:
    name: riu-searcher
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: riu_user
    password: RiuUserPassword123
    driver-class-name: oracle.jdbc.OracleDriver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer